version: 2.1

jobs:
  codeformat:
    docker:
      - image: rust:1
    steps:
      - checkout
      - restore_cache:
          key: rustfmt-cache-v0
      - run:
          name: Install rustfmt
          command: |
            rustup component add rustfmt
            cargo fmt -- --version
      - run:
          name: Check formatting
          command: |
            cargo fmt -- --check
      - save_cache:
          key: rustfmt-cache-v0
          paths:
            - "~/.cargo"
            - "./target"
  nightly:
    docker:
      - image: rust:1
    steps:
      - checkout
      - restore_cache:
          key: nightly-cache-v0
      - run:
          name: Install nightly rust
          command: |
            rustup install nightly
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
      - run:
          name: Build
          command: |
            rustup run nightly cargo build
      - run:
          name: Test
          command: rustup run nightly cargo test
      - save_cache:
          key: nightly-cache-v0
          paths:
            - "~/.cargo"
            - "./target"
  stable:
    docker:
      - image: rust:1
    steps:
      - checkout
      - restore_cache:
          key: stable-cache-v0
      - run:
          name: Install stable rust
          command: |
            rustup install stable
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
      - run:
          name: Build
          command: |
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - save_cache:
          key: stable-cache-v0
          paths:
            - "~/.cargo"
            - "./target"
  clippy:
    docker:
      - image: rust:1
    steps:
      - checkout
      - restore_cache:
          key: clippy-cache-v0
      - run:
          name: Install clippy
          command: |
            rustup component add clippy
            cargo clippy --version
      - run:
          name: Check
          command: |
            cargo clippy -- -D warnings
            # also check tests and non-default crate features
            cargo clippy --all-targets --all-features -- -D warnings
      - save_cache:
          key: clippy-cache-v0
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2
  codeformat:
    jobs:
      - codeformat
  stable:
    jobs:
      - stable
  nightly:
    jobs:
      - nightly
  clippy:
    jobs:
      - clippy
